# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-10-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='国家名称')),
                ('code', models.CharField(default='', max_length=10, verbose_name='国家简称')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='汇率')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
            },
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='图片名字', max_length=20, verbose_name='图片名字')),
                ('package', models.CharField(help_text='图片下载地址', max_length=100, verbose_name='图片下载地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='图片创建时间', verbose_name='图片创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='图片修改时间', verbose_name='图片修改时间')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=50, verbose_name='title')),
                ('author', models.CharField(help_text='author', max_length=20, verbose_name='author')),
                ('innerhtml', models.TextField(help_text='文章主体内容', max_length=3000, verbose_name='文章主体内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='文章创建时间', verbose_name='文章创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='文章修改时间', verbose_name='文章修改时间')),
                ('readed_number', models.IntegerField(default=1, help_text='阅读数', verbose_name='阅读数')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
