# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-10-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, blank=True, help_text='图片创建时间', verbose_name='图片创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgs',
            name='update_time',
            field=models.DateTimeField(auto_now=True, blank=True, help_text='图片修改时间', verbose_name='图片修改时间'),
        ),
    ]
